package provider

import (
	"context"
	"strconv"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	v1pb "buf.build/gen/go/bytebase/bytebase/protocolbuffers/go/v1"

	"github.com/bytebase/terraform-provider-bytebase/api"
	"github.com/bytebase/terraform-provider-bytebase/provider/internal"
)

func dataSourceProjectList() *schema.Resource {
	return &schema.Resource{
		Description:        "The project data source list.",
		ReadWithoutTimeout: dataSourceProjectListRead,
		Schema: map[string]*schema.Schema{
			"query": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Filter projects by name or resource id with wildcard.",
			},
			"exclude_default": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "If not include the default project in the response.",
			},
			"state": {
				Type:     schema.TypeString,
				Optional: true,
				Default:  v1pb.State_ACTIVE.String(),
				ValidateFunc: validation.StringInSlice([]string{
					v1pb.State_ACTIVE.String(),
					v1pb.State_DELETED.String(),
				}, false),
				Description: "Filter projects by state. Default ACTIVE.",
			},
			"projects": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"resource_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The project unique resource id.",
						},
						"name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The project full name in projects/{resource id} format.",
						},
						"title": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The project title.",
						},
						"enforce_issue_title": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Enforce issue title created by user instead of generated by Bytebase.",
						},
						"auto_enable_backup": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Whether to automatically enable backup.",
						},
						"skip_backup_errors": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Whether to skip backup errors and continue the data migration.",
						},
						"postgres_database_tenant_mode": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Whether to enable the database tenant mode for PostgreSQL. If enabled, the issue will be created with the pre-appended \"set role <db_owner>\" statement.",
						},
						"allow_self_approval": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Whether to allow the issue creator to self-approve the issue.",
						},
						"data_classification_config_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The data classification configuration ID for the project.",
						},
						"force_issue_labels": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Force issue labels to be used when creating an issue.",
						},
						"enforce_sql_review": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Whether to enforce SQL review checks to pass before issue creation.",
						},
						"require_issue_approval": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Whether to require issue approval before rollout.",
						},
						"require_plan_check_no_error": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Whether to require plan check to have no error before rollout.",
						},
						"allow_request_role": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Whether to allow requesting roles in this project.",
						},
						"issue_labels": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "Labels available for tagging issues in this project.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"value": {
										Type:     schema.TypeString,
										Computed: true,
									},
									"color": {
										Type:     schema.TypeString,
										Computed: true,
									},
									"group": {
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},
						"labels": {
							Type:     schema.TypeMap,
							Computed: true,
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"databases": getDatabasesSchema(true),
						"webhooks":  getWebhooksSchema(true),
					},
				},
			},
		},
	}
}

func dataSourceProjectListRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(api.Client)

	// Warning or errors can be collected in a slice type
	var diags diag.Diagnostics

	filter := &api.ProjectFilter{
		Query:          d.Get("query").(string),
		ExcludeDefault: d.Get("exclude_default").(bool),
	}
	stateString := d.Get("state").(string)
	stateValue, ok := v1pb.State_value[stateString]
	if ok {
		filter.State = v1pb.State(stateValue)
	}

	allProjects, err := c.ListProject(ctx, filter)
	if err != nil {
		return diag.FromErr(err)
	}

	projects := make([]map[string]interface{}, 0)
	for _, project := range allProjects {
		projectID, err := internal.GetProjectID(project.Name)
		if err != nil {
			return diag.FromErr(err)
		}

		proj := make(map[string]interface{})
		proj["resource_id"] = projectID
		proj["name"] = project.Name
		proj["title"] = project.Title
		proj["enforce_issue_title"] = project.EnforceIssueTitle
		proj["auto_enable_backup"] = project.AutoEnableBackup
		proj["skip_backup_errors"] = project.SkipBackupErrors
		proj["allow_self_approval"] = project.AllowSelfApproval
		proj["postgres_database_tenant_mode"] = project.PostgresDatabaseTenantMode
		proj["data_classification_config_id"] = project.DataClassificationConfigId
		proj["force_issue_labels"] = project.ForceIssueLabels
		proj["enforce_sql_review"] = project.EnforceSqlReview
		proj["require_issue_approval"] = project.RequireIssueApproval
		proj["require_plan_check_no_error"] = project.RequirePlanCheckNoError
		proj["allow_request_role"] = project.AllowRequestRole
		proj["issue_labels"] = flattenIssueLabels(project.IssueLabels)
		proj["labels"] = project.Labels

		databases, err := c.ListDatabase(ctx, project.Name, &api.DatabaseFilter{}, false)
		if err != nil {
			return diag.FromErr(err)
		}

		databaseList := flattenDatabaseList(databases)
		proj["databases"] = databaseList
		proj["webhooks"] = schema.NewSet(webhookHash, flattenWebhookList(project.Webhooks))

		projects = append(projects, proj)
	}

	if err := d.Set("projects", projects); err != nil {
		return diag.FromErr(err)
	}

	// always refresh
	d.SetId(strconv.FormatInt(time.Now().Unix(), 10))

	return diags
}
