package provider

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	"github.com/bytebase/terraform-provider-bytebase/api"
	"github.com/bytebase/terraform-provider-bytebase/provider/internal"

	v1pb "buf.build/gen/go/bytebase/bytebase/protocolbuffers/go/v1"
)

func dataSourceProject() *schema.Resource {
	return &schema.Resource{
		Description:        "The project data source.",
		ReadWithoutTimeout: dataSourceProjectRead,
		Schema: map[string]*schema.Schema{
			"resource_id": {
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: internal.ResourceIDValidation,
				Description:  "The project unique resource id.",
			},
			"title": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The project title.",
			},
			"name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The project full name in projects/{resource id} format.",
			},
			"enforce_issue_title": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Enforce issue title created by user instead of generated by Bytebase.",
			},
			"allow_self_approval": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Whether to allow the issue creator to self-approve the issue.",
			},
			"postgres_database_tenant_mode": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Whether to enable the database tenant mode for PostgreSQL. If enabled, the issue will be created with the pre-appended \"set role <db_owner>\" statement.",
			},
			"execution_retry_policy": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "The maximum number of retries for the lock timeout issue.",
			},
			"ci_sampling_size": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "The maximum databases of rows to sample during CI data validation.",
			},
			"parallel_tasks_per_rollout": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "The maximum number of parallel tasks to run during the rollout.",
			},
			"data_classification_config_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The data classification configuration ID for the project.",
			},
			"force_issue_labels": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Force issue labels to be used when creating an issue.",
			},
			"enforce_sql_review": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Whether to enforce SQL review checks to pass before issue creation.",
			},
			"require_issue_approval": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Whether to require issue approval before rollout.",
			},
			"require_plan_check_no_error": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Whether to require plan check to have no error before rollout.",
			},
			"allow_request_role": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Whether to allow requesting roles in this project.",
			},
			"allow_just_in_time_access": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Whether to allow just-in-time access in this project.",
			},
			"issue_labels": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "Labels available for tagging issues in this project.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"value": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The label value/name.",
						},
						"color": colorBlockSchema("The label color.", true),
						"group": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The group this label belongs to.",
						},
					},
				},
			},
			"labels": {
				Type:        schema.TypeMap,
				Computed:    true,
				Description: "Labels are key-value pairs that can be attached to the project.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"databases": getDatabasesSchema(true),
			"webhooks":  getWebhooksSchema(true, false),
		},
	}
}

func getWebhooksSchema(computed, hashURL bool) *schema.Schema {
	urlDescription := "The webhook URL"
	if hashURL {
		urlDescription = "The webhook URL. The plaintext value is not stored in Terraform state; only a SHA-256 digest is stored for diff detection."
	}
	description := "The webhooks in the project."
	if hashURL {
		description = "The webhooks in the project. The plaintext url is stored as a SHA-256 digest in Terraform state; webhook identity for updates uses the (title, type) pair, and duplicate (title, type) pairs are rejected at plan time."
	}

	return &schema.Schema{
		Type:        schema.TypeList,
		Optional:    !computed,
		Computed:    computed,
		Description: description,
		MinItems:    0,
		ConfigMode:  schema.SchemaConfigModeAttr,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"type": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "The webhook type. Check https://github.com/bytebase/bytebase/blob/release/3.17.0/proto/v1/v1/common.proto#L153 for support types.",
					ValidateFunc: validation.StringInSlice([]string{
						v1pb.WebhookType_SLACK.String(),
						v1pb.WebhookType_DISCORD.String(),
						v1pb.WebhookType_TEAMS.String(),
						v1pb.WebhookType_DINGTALK.String(),
						v1pb.WebhookType_FEISHU.String(),
						v1pb.WebhookType_WECOM.String(),
						v1pb.WebhookType_LARK.String(),
					}, false),
				},
				"title": {
					Type:         schema.TypeString,
					Required:     true,
					Description:  "The webhook title",
					ValidateFunc: validation.StringIsNotEmpty,
				},
				"name": {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The webhook full name in projects/{resource id}/webhooks/{id} format.",
				},
				"url": {
					Type:         schema.TypeString,
					Required:     true,
					Sensitive:    hashURL,
					StateFunc:    webhookURLHashStateFunc(hashURL),
					Description:  urlDescription,
					ValidateFunc: validation.IsURLWithHTTPorHTTPS,
				},
				"direct_message": {
					Type:        schema.TypeBool,
					Optional:    true,
					Description: "If direct_message is set, the notification is sent directly to the persons and url will be ignored. Require IM integration for this function to work.",
				},
				"notification_types": {
					Type:        schema.TypeSet,
					Required:    true,
					MinItems:    1,
					Description: "notification_types is the list of activities types that the webhook is interested in. Bytebase will only send notifications to the webhook if the activity type is in the list.",
					Elem: &schema.Schema{
						Type:        schema.TypeString,
						Description: "Check https://github.com/bytebase/bytebase/blob/release/3.17.0/proto/v1/v1/project_service.proto for support types.",
						ValidateFunc: validation.StringInSlice([]string{
							v1pb.Activity_ISSUE_CREATED.String(),
							v1pb.Activity_ISSUE_APPROVED.String(),
							v1pb.Activity_ISSUE_APPROVAL_REQUESTED.String(),
							v1pb.Activity_ISSUE_SENT_BACK.String(),
							v1pb.Activity_PIPELINE_FAILED.String(),
							v1pb.Activity_PIPELINE_COMPLETED.String(),
						}, false),
					},
				},
			},
		},
	}
}

func webhookURLHashStateFunc(enabled bool) schema.SchemaStateFunc {
	if !enabled {
		return nil
	}
	return func(v interface{}) string {
		s, ok := v.(string)
		if !ok || s == "" {
			return ""
		}
		sum := sha256.Sum256([]byte(s))
		return hex.EncodeToString(sum[:])
	}
}

func getDatabasesSchema(computed bool) *schema.Schema {
	return &schema.Schema{
		Type:        schema.TypeSet,
		Computed:    computed,
		Optional:    !computed,
		Description: "The databases full name in the resource.",
		Elem: &schema.Schema{
			Type: schema.TypeString,
		},
	}
}

func dataSourceProjectRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(api.Client)
	projectName := fmt.Sprintf("%s%s", internal.ProjectNamePrefix, d.Get("resource_id").(string))
	project, err := c.GetProject(ctx, projectName)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(project.Name)
	return setProject(ctx, c, d, project, false)
}

func flattenDatabaseList(databases []*v1pb.Database) []interface{} {
	dbList := []interface{}{}
	for _, database := range databases {
		dbList = append(dbList, database.Name)
	}
	return dbList
}

// flattenWebhookList builds the state representation of a project's webhooks.
//
// When hashURL is true (resource read path), the url field is represented as
// a SHA-256 digest so Terraform can diff URL changes without storing plaintext
// webhook secrets in state. For the data source path (hashURL=false), url is
// included as returned by the API.
func flattenWebhookList(webhooks []*v1pb.Webhook, hashURL bool) []interface{} {
	hashURLState := webhookURLHashStateFunc(hashURL)
	rawWebhooks := []interface{}{}
	for _, webhook := range webhooks {
		rawWebhook := make(map[string]interface{})
		rawWebhook["title"] = webhook.Title
		rawWebhook["type"] = webhook.Type.String()
		if hashURLState != nil {
			rawWebhook["url"] = hashURLState(webhook.Url)
		} else {
			rawWebhook["url"] = webhook.Url
		}
		rawWebhook["name"] = webhook.Name
		rawWebhook["direct_message"] = webhook.DirectMessage

		// Convert notification types to interface slice, then wrap in Set
		notificationTypes := []interface{}{}
		for _, notificationType := range webhook.NotificationTypes {
			notificationTypes = append(notificationTypes, notificationType.String())
		}
		// Use schema.NewSet for consistency with the schema definition
		rawWebhook["notification_types"] = schema.NewSet(schema.HashString, notificationTypes)

		rawWebhooks = append(rawWebhooks, rawWebhook)
	}
	return rawWebhooks
}

func setProject(
	ctx context.Context,
	client api.Client,
	d *schema.ResourceData,
	project *v1pb.Project,
	hashURL bool,
) diag.Diagnostics {
	tflog.Debug(ctx, "[read project] start reading project", map[string]interface{}{
		"project": project.Name,
	})

	databases, err := client.ListDatabase(ctx, project.Name, &api.DatabaseFilter{}, true)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(project.Name)

	projectID, err := internal.GetProjectID(project.Name)
	if err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("resource_id", projectID); err != nil {
		return diag.Errorf("cannot set resource_id for project: %s", err.Error())
	}
	if err := d.Set("title", project.Title); err != nil {
		return diag.Errorf("cannot set title for project: %s", err.Error())
	}
	if err := d.Set("name", project.Name); err != nil {
		return diag.Errorf("cannot set name for project: %s", err.Error())
	}
	if err := d.Set("title", project.Title); err != nil {
		return diag.Errorf("cannot set title for project: %s", err.Error())
	}
	if err := d.Set("enforce_issue_title", project.EnforceIssueTitle); err != nil {
		return diag.Errorf("cannot set enforce_issue_title for project: %s", err.Error())
	}
	if err := d.Set("allow_self_approval", project.AllowSelfApproval); err != nil {
		return diag.Errorf("cannot set allow_self_approval for project: %s", err.Error())
	}
	if err := d.Set("postgres_database_tenant_mode", project.PostgresDatabaseTenantMode); err != nil {
		return diag.Errorf("cannot set postgres_database_tenant_mode for project: %s", err.Error())
	}
	if project.ExecutionRetryPolicy != nil {
		if err := d.Set("execution_retry_policy", project.ExecutionRetryPolicy.MaximumRetries); err != nil {
			return diag.Errorf("cannot set execution_retry_policy for project: %s", err.Error())
		}
	}
	if err := d.Set("ci_sampling_size", project.CiSamplingSize); err != nil {
		return diag.Errorf("cannot set ci_sampling_size for project: %s", err.Error())
	}
	if err := d.Set("parallel_tasks_per_rollout", project.ParallelTasksPerRollout); err != nil {
		return diag.Errorf("cannot set parallel_tasks_per_rollout for project: %s", err.Error())
	}
	if err := d.Set("data_classification_config_id", project.DataClassificationConfigId); err != nil {
		return diag.Errorf("cannot set data_classification_config_id for project: %s", err.Error())
	}
	if err := d.Set("force_issue_labels", project.ForceIssueLabels); err != nil {
		return diag.Errorf("cannot set force_issue_labels for project: %s", err.Error())
	}
	if err := d.Set("enforce_sql_review", project.EnforceSqlReview); err != nil {
		return diag.Errorf("cannot set enforce_sql_review for project: %s", err.Error())
	}
	if err := d.Set("require_issue_approval", project.RequireIssueApproval); err != nil {
		return diag.Errorf("cannot set require_issue_approval for project: %s", err.Error())
	}
	if err := d.Set("require_plan_check_no_error", project.RequirePlanCheckNoError); err != nil {
		return diag.Errorf("cannot set require_plan_check_no_error for project: %s", err.Error())
	}
	if err := d.Set("allow_request_role", project.AllowRequestRole); err != nil {
		return diag.Errorf("cannot set allow_request_role for project: %s", err.Error())
	}
	if err := d.Set("allow_just_in_time_access", project.AllowJustInTimeAccess); err != nil {
		return diag.Errorf("cannot set allow_just_in_time_access for project: %s", err.Error())
	}
	if err := d.Set("issue_labels", flattenIssueLabels(project.IssueLabels)); err != nil {
		return diag.Errorf("cannot set issue_labels for project: %s", err.Error())
	}
	if err := d.Set("labels", project.Labels); err != nil {
		return diag.Errorf("cannot set labels for project: %s", err.Error())
	}

	startTime := time.Now()
	databaseList := flattenDatabaseList(databases)
	if err := d.Set("databases", databaseList); err != nil {
		return diag.Errorf("cannot set databases for project: %s", err.Error())
	}
	tflog.Debug(ctx, "[read project] set project databases", map[string]interface{}{
		"project":   project.Name,
		"databases": len(databases),
		"ms":        time.Since(startTime).Milliseconds(),
	})

	if err := d.Set("webhooks", flattenWebhookList(project.Webhooks, hashURL)); err != nil {
		return diag.Errorf("cannot set webhooks for project: %s", err.Error())
	}

	return nil
}
