name: build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - run: go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          args: -v
          skip-cache: true
  go-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Verify tidy
        run: |
          go mod tidy
          git diff --exit-code
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.*"
          terraform_wrapper: false
      - run: |
          go generate ./...
          go test -v -cover ./...
        env:
          TF_ACC: "1"
          # Test uses mock service, and any value should work
          BYTEBASE_SERVICE_ACCOUNT: "terraform@service.bytebase.com"
          BYTEBASE_SERVICE_KEY: "12345"
          BYTEBASE_URL: "https://bytebase.example.com"
